### ISSUE TITLE
提供一个shell 自动下载和安装，更具设备下载指定执行文件

### ISSUE THREAD

**Issue by xiaocode337317439** [jicheng1014/go-fir-cli#1]
提供一个shell 自动下载和安装，更具设备下载指定执行文件

**Comment by jicheng1014** [comment]
![image](https://user-images.githubusercontent.com/1264913/224932631-1797b317-ebb4-41cc-9aaa-bd13bcbc4b7d.png)
![image](https://user-images.githubusercontent.com/1264913/224932702-764bb9a5-ce92-47d4-891b-d9734c533ac3.png)
