### ISSUE TITLE
`go_fir_cli upload` 需要token

### ISSUE THREAD

**Issue by tbxark** [jicheng1014/go-fir-cli#2]
不是很理解你们的设计，有`go_fir_cli login`，结果登陆了啥用没有，调用`go_fir_cli upload`还得传一次token。

**Comment by xiaocode337317439** [comment]
使用起来和 fir-cli 一样吗？只是换了个语言实现？

**Comment by jicheng1014** [comment]
> 不是很理解你们的设计，有`go_fir_cli login`，结果登陆了啥用没有，调用`go_fir_cli upload`还得传一次token。

login 目前就只能看看 token 是否能用, 其实是当时写的时候就是拿来验证 copilot 是否能搞掂这个事情的

golang 不熟主要是.... 基本是靠 chatgpt 和 copilot 写的

欢迎老哥 PR 来实现 login 持久化

**Comment by jicheng1014** [comment]
> 使用起来和 fir-cli 一样吗？只是换了个语言实现？

README 中说明了, 只是基本功能类似, 换了个语言实现的, 二进制版本的不需要重新编译以及安装依赖

整个 firim 都是基于 ruby 的, 所以当年开发 fir-cli 也是用 ruby 写的

解释性语言嘛, 要是注重代码安全, 可以使用 fir-cli 版本, 代码即最后运行内容, 

如果图方便使用, 可以用go-fir-cli , 无依赖, 直接用二进制, 当然我也是用 github action 编译的, 没啥私货夹带,  信不过的话自己编译也行, 也很方便快捷

**Comment by tbxark** [comment]
> > 不是很理解你们的设计，有`go_fir_cli login`，结果登陆了啥用没有，调用`go_fir_cli upload`还得传一次token。
> 
> login 目前就只能看看 token 是否能用, 其实是当时写的时候就是拿来验证 copilot 是否能搞掂这个事情的
> 
> golang 不熟主要是.... 基本是靠 chatgpt 和 copilot 写的
> 
> 欢迎老哥 PR 来实现 login 持久化

好的，不介意的话之后我提个pr。这里提个小建议，可以把`go.mod`的项目名字改成`github.com/PGYER/go-fir-cli` 这样就能直接用`go install `一键编译安装了。


```
➜  go install github.com/PGYER/go-fir-cli@latest
go: downloading github.com/PGYER/go-fir-cli v0.0.0-20230309075632-39b8d5696d59
go: github.com/PGYER/go-fir-cli@latest: github.com/PGYER/go-fir-cli@v0.0.0-20230309075632-39b8d5696d59: parsing go.mod:
	module declares its path as: betaqr.com/go_fir_cli
	        but was required as: github.com/PGYER/go-fir-cli
➜ go install betaqr.com/go_fir_cli@latest
go: betaqr.com/go_fir_cli@latest: unrecognized import path "betaqr.com/go_fir_cli": parse https://betaqr.com/go_fir_cli?go-get=1: no go-import meta tags ()
```


举例

```shell
go install github.com/TBXark/mweb-export@latest
```

**Comment by jicheng1014** [comment]
> > > 不是很理解你们的设计，有`go_fir_cli login`，结果登陆了啥用没有，调用`go_fir_cli upload`还得传一次token。
> > 
> > 
> > login 目前就只能看看 token 是否能用, 其实是当时写的时候就是拿来验证 copilot 是否能搞掂这个事情的
> > golang 不熟主要是.... 基本是靠 chatgpt 和 copilot 写的
> > 欢迎老哥 PR 来实现 login 持久化
> 
> 好的，不介意的话之后我提个pr。这里提个小建议，可以把`go.mod`的项目名字改成`github.com/PGYER/go-fir-cli` 这样就能直接用`go install `一键编译安装了。
> 
> ```
> ➜  go install github.com/PGYER/go-fir-cli@latest
> go: downloading github.com/PGYER/go-fir-cli v0.0.0-20230309075632-39b8d5696d59
> go: github.com/PGYER/go-fir-cli@latest: github.com/PGYER/go-fir-cli@v0.0.0-20230309075632-39b8d5696d59: parsing go.mod:
> 	module declares its path as: betaqr.com/go_fir_cli
> 	        but was required as: github.com/PGYER/go-fir-cli
> ➜ go install betaqr.com/go_fir_cli@latest
> go: betaqr.com/go_fir_cli@latest: unrecognized import path "betaqr.com/go_fir_cli": parse https://betaqr.com/go_fir_cli?go-get=1: no go-import meta tags ()
> ```
> 
> 举例
> 
> ```shell
> go install github.com/TBXark/mweb-export@latest
> ```

多谢指教, 期待PR

**Comment by jicheng1014** [comment]
已更新
